stages:
  - build
  - package
  - deploy

image: liuchong/rustup:nightly

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

cache:
  paths:
    - target/
    - .cargo/

build:
  stage: build
  before_script:
    - export PATH="$PATH:$CARGO_HOME/bin"
    - rustup component add clippy rustfmt
    - cargo install cargo-update cargo-make || true
    - cargo install-update -a
  script:
    - cargo make check-release-flow
    - cp -r target/package/release evredis
  artifacts:
    expire_in: 1 week
    paths:
      - evredis

dockerize:
  stage: package
  services:
    - docker:dind
  image: docker:stable
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  after_script:
    - docker logout $CI_REGISTRY
  only:
    - develop
    - master
